swagger: '2.0'
info:
  description: Awards class.
  version: 1.0.0
  title: Swagger TBFY API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: fyedro@fi.upm.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: awards.swagger.io
basePath: /v2
tags:
  - name: awards
    description: Awards in Public Procurement
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
  - http
paths:
  /awards/{id}':
    get:
      tags:
        - awards
      summary: Find award by ID
      description: Returns a single award
      operationId: getAwardsById
      produces:
        - application/json
      parameters:
        - name: AwardsId
          in: path
          description: ID of award to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Awards'
        '400':
          description: Invalid ID supplied
        '404':
          description: Award not found
      security:
        - api_key: []
securityDefinitions:
  contract_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:contracts': modify awards
      'read:contracts': read your awards
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      description:
        type: string
      status:
        type: string
      date:
        type: object
      value:
        type: object
      suppliers:
        type: array
        minItems: 1
        uniqueItems: true
        items:
          type: string
          enum: [ "1", "2", "3" ]
      items:
        type: array
      datesigned:
        type: object
    xml:
      name: Category
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
    xml:
      name: Tag
  Awards:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/Category'
      name:
        type: string
        example: furniture
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      status:
        type: string
        description: awards status
        enum:
          - available
          - pending
          - sold
    xml:
      name: awards
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
