swagger: '2.0'
info:
  description: API example.
  version: 1.0.0
  title: Swagger TBFY API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: fyedro@fi.upm.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: contract.swagger.io
basePath: /v2
tags:
  - name: contract
    description: Public procurement contracts
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
  - http
paths:
  /contract:
    get:
      tags:
        - contract
      summary: Gets a list of contracts.
      parameters:
        - $ref: '#/components/parameters/status'
        - $ref: '#/components/parameters/before'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: OK
  '/contract/{id}''':
    get:
      tags:
        - contract
      summary: Find contract by ID
      description: Returns a single contract
      operationId: getContractById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contract to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid ID supplied
        '404':
          description: Contract not found
components:
  parameters:
    status:
      in: query
      name: status
      required: false
      schema:
        $ref: '#/definitions/Status'
      description: The status of contracts.
    before:
      in: query
      name: before
      required: false
      schema:
        type: string
      description: ISO 8601
    after:
      in: query
      name: after
      required: false
      schema:
        type: string
      description: ISO 8601
definitions:
  Contract:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      award:
        type: object
        properties:
          id:
            type: integer
            format: int64
          uri: 
            type: string
      description:
        type: string
      status:
        $ref: '#/definitions/Status'
      period:
        type: object
        properties:
          start:
            $ref: '#/definitions/DateTime'
          end:
            $ref: '#/definitions/DateTime'
      dateSigned:
        $ref: '#/definitions/DateTime'
      value:
        type: object
        properties:
          amount:
            type: integer
          currency:
            description: ISO-4217
            type: string
    xml:
      name: Contract
  Status:
    type: string
    enum: [pending, active, cancelled, terminated]
  DateTime:
    type: object
    properties:
      date: 
        type: string
        description: ISO 8601
      time: 
        type: integer
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
