swagger: '2.0'
info:
  description: API example.
  version: 1.0.0
  title: Swagger TBFY API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: fyedro@fi.upm.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: contract.swagger.io
basePath: /v2
tags:
  - name: contract
    description: Public procurement contracts
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
  - http
paths:
  /contract:
    get:
      tags:
        - contract
      summary: Contracts list
      description: Returns the full list of contracts
      operationId: getContract
      produces:
        - application/json
      parameters:
        - name: contract
          in: path
          description: List of contract to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid ID supplied
        '404':
          description: Contract not found
      security:
        - api_key: []
securityDefinitions:
  contract_auth:
    type: oauth2
    authorizationUrl: 'https://github.com/TBFY'
    flow: implicit
    scopes:
      'write:contracts': modify contracts
      'read:contracts': read your contracts
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  Contract:
    type: object
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/Category'
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      status:
        type: string
        description: contract status
        enum:
          - available
          - pending
          - sold
    xml:
      name: Contract
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
