swagger: '2.0'
info:
  description: API example.
  version: 1.0.0
  title: Swagger TBFY API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: fyedro@fi.upm.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: contract.swagger.io
basePath: /v2
tags:
  - name: contract
    description: Public procurement contracts
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
  - http
paths:
  /contract:
    get:
      tags:
        - contract
      summary: Gets a list of contracts.
      parameters:
        - $ref: '#/components/parameters/status'
        - $ref: '#/components/parameters/before'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: OK
  /contract/{id}:
    get:
      tags:
        - contract
      summary: Find contract by ID
      description: Returns a single contract
      operationId: getContractById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contract to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid ID supplied
        '404':
          description: Contract not found
  /contract/{id}/amendment:  
    get:
      tags:
        - contract
      summary: Amendments of a contract to return
      description: Returns a the amendments of a contract
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contract to return
          required: true
          type: integer
          format: int64
        - $ref: '#/components/parameters/before'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Amendment'
  /contract/{id}/document:  
    get:
      tags:
        - contract
      summary: Documents of a contract to return
      description: Returns a the documents of a contract
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contract to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Document'
  /contract/{id}/item:  
    get:
      tags:
        - contract
      summary: Items of a contract to return
      description: Returns a the items of a contract
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contract to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Item'
  /organisation:
    get:
      tags:
        - organisation
      summary: Gets a list of organisations
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                legalname:
                  type: string
                uri:
                  type: string
  /organisation/{id}:
    get:
      tags:
        - organisation
      summary: Find an organisation by ID
      description: Returns a single organisation
      operationId: getOrganisationById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of organisation to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Organisation'
        '400':
          description: Invalid ID supplied
        '404':
          description: Organisation not found
components:
  parameters:
    status:
      in: query
      name: status
      required: false
      schema:
        $ref: '#/definitions/Status'
      description: The status of contracts.
    before:
      in: query
      name: before
      required: false
      schema:
        type: string
      description: ISO 8601
    after:
      in: query
      name: after
      required: false
      schema:
        type: string
      description: ISO 8601
definitions:
  Contract:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      award:
        type: object
        properties:
          id:
            type: integer
            format: int64
          uri:
            type: string
      description:
        type: string
      status:
        $ref: '#/definitions/Status'
      period:
        type: object
        properties:
          start:
            $ref: '#/definitions/DateTime'
          end:
            $ref: '#/definitions/DateTime'
      dateSigned:
        $ref: '#/definitions/DateTime'
      value:
        type: object
        properties:
          amount:
            type: integer
          currency:
            description: ISO-4217
            type: string
    xml:
      name: Contract
  Amendment:
    type: object 
    required: 
      - title
    properties:
      id:
        type: integer
        format: int64   
      date:
        $ref: '#/definitions/DateTime'
      rationale:
        type: string 
      description:
        type: string    
      amendsReleaseID:
        type: string 
      releaseID:
        type: string 
      changes:
        type: array 
        items:
          type: object 
          properties:
            name:
              type: string 
  Document:
    type: object 
    required: 
      - title
      - id
    properties:
      id:
        type: integer
        format: int64 
      documenttype:
        type: string 
      title:
        type: string 
      description:
        type: string 
      url:
        type: string 
        format: uri
      datepublished:
        $ref: '#/definitions/DateTime'
      datemodified:
        $ref: '#/definitions/DateTime'
      format:
        type: string    
      language:
        type: string  
  Item:
    type: object 
    required: 
      - description
      - id
    properties:
      id:
        type: integer
        format: int64 
      description:
        type: string 
      classification:
        type: object 
        properties: 
          scheme:
            type: string
          id:
            type: integer
            format: int64
          description:
            type: string
          uri:
            type: string
      quantity:
        type: number 
      unit:
        type: string
  Organisation:
    type: object 
    required: 
      - name
      - id
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      identifier:
        type: object
        required:
          - id
          - legalname
        properties:
          scheme:
            type: string
          id:
            type: string
          legalname:
            type: string
          uri:
            type: string
      additionalIdentifiers:
        type: object
        required:
          - id
          - legalname
        properties:
          scheme:
            type: string
          id:
            type: string
          name:
            type: string
          uri:
            type: string
      address:
        type: object
        required:
          - streetaddress
          - postalcode
        properties:
          streetaddress:
            type: string
          locality:
            type: string
          region:
            type: string
          postalcode:
            type: string     
          countryname:
            type: string      
      contactpoint:
        type: object
        required:
          - name
        properties:
          name:
            type: string
          email:
            type: string
          telephone:
            type: string
          faxnumber:
            type: string     
          url:
            type: string 
            format: uri
      roles:
        type: array 
        items:
          type: object 
          properties:
            partyroles:
              type: string 
      details:
        type: object
  Status:
    type: string
    enum:
      - pending
      - active
      - cancelled
      - terminated
  DateTime:
    type: object
    properties:
      date:
        type: string
        description: ISO 8601
      time:
        type: integer
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
