swagger: '2.0'
info:
  description: API example.
  version: 1.0.0
  title: Swagger TBFY API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: fyedro@fi.upm.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: contract.swagger.io
basePath: /v2
tags:
  - name: contract
    description: Public procurement contracts
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
  - http
paths:
  /contract:
    post:
      tags:
        - contract
      summary: Add a new contract
      description: ''
      operationId: addContract
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contract object to be added
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        '405':
          description: Invalid input
      security:
        - contract_auth:
            - 'write:contracts'
            - 'read:contracts'
    put:
      tags:
        - contract
      summary: Update an existing contract
      description: ''
      operationId: updateContract
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contract object to be added
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Contract not found
        '405':
          description: Validation exception
      security:
        - contract_auth:
            - 'write:contracts'
            - 'read:contracts'
  /contract/{contractId}:
    get:
      tags:
        - contract
      summary: Find contract by ID
      description: Returns a single contract
      operationId: getContractById
      produces:
        - application/json
      parameters:
        - name: contractId
          in: path
          description: ID of contract to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid ID supplied
        '404':
          description: Contract not found
      security:
        - api_key: []
    post:
      tags:
        - contract
      summary: Updates a contract with form data
      description: ''
      operationId: updateContractWithForm
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: contractId
          in: path
          description: ID of contract that needs to be updated
          required: true
          type: integer
          format: int64
        - name: name
          in: formData
          description: Updated name of the contract
          required: false
          type: string
        - name: status
          in: formData
          description: Updated status of the contract
          required: false
          type: string
      responses:
        '405':
          description: Invalid input
      security:
        - contract_auth:
            - 'write:contracts'
            - 'read:contracts'
securityDefinitions:
  contract_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:contracts': modify contracts
      'read:contracts': read your contracts
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  Contract:
    type: object
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/Category'
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      status:
        type: string
        description: contract status
        enum:
          - available
          - pending
          - sold
    xml:
      name: Contract
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
